### ISSUE TITLE
Apache User cannot be root

### ISSUE THREAD

**Issue by stewartwebb** [SocialEngine/docker-php-apache#3] opened 2016-04-25 17:10 UTC
Hi,

I was trying to run your php-5.6 version and got this error

```
[Apache User] Set Apache user to root and group to root
AH00526: Syntax error on line 9 of /etc/apache2/apache2.conf:
Error:\tApache has not been designed to serve pages while\n\trunning as root.  There are known race conditions that\n\twill allow any local user to read any file on the system.\n\tIf you still desire to serve pages as root then\n\tadd -DBIG_SECURITY_HOLE to the CFLAGS env variable\n\tand then rebuild the server.\n\tIt is strongly suggested that you instead modify the User\n\tdirective in your httpd.conf file to list a non-root\n\tuser.\n
```

Line 9 of apache2.conf is: `User ${APACHE_RUN_USER}`

Is there a way to  get around this or a fix? Thanks

**Comment by smazurov** [comment] 2016-04-26 18:14
@stewartwebb 

There is a detection of `/app` folder going on, and the apache runs as same user as the owner of that folder/volume. That means that if you mount a folder that has `uid` of 1, it assumes its root. If you can control the permission of the `/app` volume, you can avoid this issue.

I've seen some issues related to having containers share a volume (i.e. have 3 containers, 2 'apache' containers and 1 volume container) and in that case, the `uid` is 1 no matter what you do. If you're in that boat I can investigate and see if I can come up with a fix.

Do you have a reproducible test I can debug?

**Comment by smazurov** [comment] 2016-05-03 02:49
I'm assuming by your reaction, you've figured it out, so I'll close this. Thank you for using this project and opening up an issue!

**Closed as completed by smazurov** 2016-05-03 02:49 UTC
Labels: question

**Comment by stewartwebb** [comment] 2016-05-05 16:19
Yes, sorry. I fiddled around with it till I had it working. Thanks for the Dockerfile!

**Comment by charabaruk** [comment] 2017-03-30 17:23
This is an issue when running Docker on Windows because files are always copied and volumes are always mounted with root:root ownership.

@stewartwebb do you remember what you did to solve the issue? Could you document it? It might help for we the Windows peons.

**Comment by Danno040** [comment] 2017-03-31 16:35
I would think the most direct way to work around the problem on Windows is to create a child image that runs `chown` on the `/app` directory. Like:

```
FROM socialengine/php-apache:5.6

COPY . /app

RUN chown -R www-data:www-data /app

RUN composer install
```
